#! /bin/sh
### BEGIN INIT INFO
# Provides:          visicam
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start/stop visicam
# Description:       A Java application, that turns a webcam into a VisiCut compatible network camera with marker detection and perspective correction.
#		     Uses OpenCV through JavaCV
### END INIT INFO

# Author: Julian Neureuther <julian@neureuther.eu>

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="camera for visicut"
NAME=visicam
# Edit according to your installation
VISICAM_ROOT=/opt/VisiCam/
VISICAM_JAR=dist/VisiCam.jar
#
DAEMON=/usr/bin/java
DAEMON_ARGS="-jar $VISICAM_JAR --nogui"
LOGFILE=/var/log/visicam.log
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

DAEMONUSER=visicam
DAEMONGROUP=visicam

# Exit if the package is not installed / symlink not set
[ -x "$DAEMON" ] || exit 0

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

#
# Function that starts the daemon/service
#
do_start()
{
	# Return
	#   0 if daemon has been started
	#   1 if daemon was already running //TODO
	#   2 if daemon could not be started

	#check if all files + dirs exist
	if [ ! -e $LOGFILE ]; then
		touch $LOGFILE || return 2
		chown $DAEMONUSER:$DAEMONGROUP $LOGFILE || return 2
	elif [ ! -e $PIDFILE ]; then
		touch $PIDFILE || return 2
		#chown $DAEMONUSER:$DAEMONGROUP $PIDFILE || return 2
	fi

	#//TODO: check if daemon is already running
	#start-stop-daemon --start --quiet --chuid $DAEMONUSER --pidfile $PIDFILE  --background --startas /bin/bash -- -c "cd $VISICAM_ROOT && exec $DAEMON $DAEMON_ARGS" --test > /dev/null \
	#	|| return 1
	start-stop-daemon --start --quiet --chuid $DAEMONUSER --make-pid --pidfile $PIDFILE --background --startas /bin/bash -- -c "cd $VISICAM_ROOT && exec $DAEMON $DAEMON_ARGS > /var/log/visicam.log 2>&1" \
		|| return 2
}

#
# Function that stops the daemon/service
#
do_stop()
{
	# Return
	#   0 if daemon has been stopped
	#   1 if daemon was already stopped
	#   2 if daemon could not be stopped
	#   other if a failure occurred
	start-stop-daemon --stop --quiet --oknodo --retry=TERM/30/KILL/5 --pidfile $PIDFILE
	RETVAL="$?"
	[ "$RETVAL" = 2 ] && return 2

	rm -f $PIDFILE
	return "$RETVAL"
}

do_reload() {
	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
	return 0
}

case "$1" in
  start)
	log_daemon_msg "Starting $DESC" "$NAME"
	do_start
	case "$?" in
		0|1) log_end_msg 0 ;;
		2) [ log_end_msg 1 ;;
	esac
	;;
  stop)
	log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop
	case "$?" in
		0|1) log_end_msg 0 ;;
		2) log_end_msg 1 ;;
	esac
	;;
  status)
	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
	;;
  restart|force-reload)
	#
	# If the "reload" option is implemented then remove the
	# 'force-reload' alias
	#
	log_daemon_msg "Restarting $DESC" "$NAME"
	do_stop
	case "$?" in
	  0|1)
		do_start
		case "$?" in
			0) log_end_msg 0 ;;
			1) log_end_msg 1 ;; # Old process is still running
			*) log_end_msg 1 ;; # Failed to start
		esac
		;;
	  *)
		# Failed to stop
		log_end_msg 1
		;;
	esac
	;;
  *)
	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
	exit 3
	;;
esac

:

