#!/bin/bash
### BEGIN INIT INFO
# Provides:          visicam
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     false
# Short-Description: Start/Restart/Stop VisiCam service
### END INIT INFO

#    This file is part of VisiCam. (https://github.com/t-oster/VisiCam)
#
#    VisiCam is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Lesser General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    VisiCam is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public License
#    along with VisiCam.  If not, see <http://www.gnu.org/licenses/>.

# ##################################################################
# START / RESTART / STOP VISICAM
# ##################################################################

VISICAMPATH="TEMPLATE-DUMMY"

case $1 in
    start)
        echo "Starting VisiCam..."
        "$VISICAMPATH/start.sh"
        ;;
    stop)
        echo "Stopping VisiCam..."
        "$VISICAMPATH/stop.sh"
        ;;
    restart)
        echo "Restarting VisiCam..."
        "$VISICAMPATH/stop.sh"
        "$VISICAMPATH/start.sh"
        ;;
    *)
        echo "Usage: $0 {start|restart|stop}"
        ;;
esac

# Exit correctly without errors
exit 0